version: '2'
services:
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - '9090:9090'
    container_name: prometheus
    restart: always
    volumes:
      - '$HOME/Deqode/prometheus.yml:/etc/prometheus/prometheus.yml'
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - '3000:3000'
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - '$HOME/Deqode/grafana.ini:/etc/grafana/grafana.ini'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@email.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    - PGADMIN_LISTEN_PORT=5050
    ports:
    - "5050:5050"
volumes:
  postgres-db:
    driver: local
  data: